update goreleaser config (#407)
The older goreleaser config is no longer supported.
```
GoReleaser latest installed successfully
/opt/hostedtoolcache/goreleaser-action/2.3.2/x64/goreleaser release --clean
  • only configurations files on  version: 2  are supported, yours is  version: 0 , please update your configuration
  ⨯ release failed after 0s                  error=only configurations files on  version: 2  are supported, yours is  version: 0 , please update your configuration
Error: The process '/opt/hostedtoolcache/goreleaser-action/2.3.2/x64/goreleaser' failed with exit code 1
```